### ISSUE TITLE
Login Session hijack - Assurance case

### ISSUE THREAD

**Issue by sanne88** [sanne88/cyber8420projectopenmrs#19]

**Comment by CyberSecurity2024** [comment]
Sahithi,

  Good morning. Thank you all for your good communication through the
project and for working with me. I just thought you should know I am no
longer a part of the program so you can take me off your team.

Best Regards,
Carl Hofstrom

**Comment by sanne88** [comment]
Hey Carl,

Thanks so much for getting back to me. It was very easy working with you
and wish you all the best for your future endeavors.

Thanks,
Sahithi anne
